services:
  api:
    container_name: api
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    restart: always
    env_file:
      - .env
    networks:
      - scx_network
    ports:
      - 8000:${API_PORT}

  docs:
    container_name: docs
    build:
      context: .
      dockerfile: ./apps/docs/Dockerfile
    restart: always
    depends_on:
      - api
    ports:
      - 3000:80
    networks:
      - scx_network

networks:
  scx_network:
    driver: bridge
