services:
  mailserver:
    build:
      context: .
      dockerfile: apps/mailserver/Dockerfile
    container_name: mailserver
    ports:
      - "25:25"
      - "587:587"
    hostname: ${MAILSERVER_HOSTNAME}
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - scx-network

networks:
  scx-network:
    driver: bridge
