name: Database Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    paths:
      - "packages/db/**"

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:17
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: satellite_cx_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "24"
          cache: "pnpm"

      - uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: pnpm install --filter db...

      - name: Setup test environment
        run: |
          echo "DATABASE_URL=postgresql://postgres:postgres@localhost:5432/satellite_cx_test" >> $GITHUB_ENV
          echo "RLS_CLIENT_DATABASE_URL=postgresql://postgres:postgres@localhost:5432/satellite_cx_test" >> $GITHUB_ENV
          echo "ENABLE_RLS=true" >> $GITHUB_ENV
          echo "POSTGRES_RLS_USER=postgres" >> $GITHUB_ENV
          echo "POSTGRES_RLS_PASSWORD=postgres" >> $GITHUB_ENV
          echo "NODE_ENV=test" >> $GITHUB_ENV

      - name: Push database schema
        run: pnpm db:push

      - name: Run tests
        run: pnpm test --filter db

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: db-test-results
          path: packages/db/test-results.xml
          retention-days: 30
